// SPDX-FileCopyrightText: 2026 Marcus Baw and Baw Medical Ltd
// SPDX-License-Identifier: AGPL-3.0-or-later

//! The calculator implementations.
//!
//! Each module exposes a strongly-typed `Input` struct, a pure `compute`
//! function, a `build_response` adapter to [`crate::CalculationResponse`], and a
//! unit struct implementing [`crate::Calculator`]. Register new calculators in
//! [`crate::all`].

pub mod abcd2;
pub mod abpi;
pub mod alcohol_units;
pub mod alvarado;
pub mod amts;
pub mod anion_gap;
pub mod apache2;
pub mod apgar;
pub mod asa_physical_status;
pub mod ascvd;
pub mod asrs;
pub mod audit;
pub mod auditc;
pub mod barthel;
pub mod basdai;
pub mod binet;
pub mod bmi;
pub mod bode;
pub mod body_fat_circumference;
pub mod body_surface_area;
pub mod braden;
pub mod caprini;
pub mod centor;
pub mod cha2ds2_va;
pub mod cha2ds2vasc;
pub mod chalice;
pub mod charlson;
pub mod child_pugh;
pub mod ciwa_ar;
pub mod ckd_risk;
pub mod cockcroft_gault;
pub mod corrected_calcium;
pub mod corrected_sodium;
pub mod cows;
pub mod curb65;
pub mod das28;
pub mod egfr;
pub mod ehra;
pub mod energy_requirement;
pub mod epds;
pub mod euroscore2;
pub mod familial_hypercholesterolaemia;
pub mod fena;
pub mod feverpain;
pub mod fib4;
pub mod findrisc;
pub mod four_ts;
pub mod fourat;
pub mod free_water_deficit;
pub mod gad7;
pub mod gcs;
pub mod glasgow_blatchford;
pub mod gleason;
pub mod grace;
pub mod hasbled;
pub mod heart;
pub mod hinchey;
pub mod homa_ir;
pub mod ipss;
pub mod isth_overt_dic;
pub mod khorana;
pub mod ldl_cholesterol;
pub mod lrinec;
pub mod max_heart_rate;
pub mod meld;
pub mod meld_3;
pub mod mrc_dyspnoea;
pub mod news2;
pub mod nhfs;
pub mod npi;
pub mod nyha;
pub mod one_rep_max;
pub mod padua;
pub mod perc;
pub mod phq9;
pub mod psa_density;
pub mod qfracture;
pub mod qrisk3;
pub mod qsofa;
pub mod rcri;
pub mod relative_fat_mass;
pub mod sofa;
pub mod timi;
pub mod uacr;
pub mod ukeld;
pub mod waist_to_height_ratio;
pub mod waist_to_hip_ratio;
pub mod waterlow;
pub mod wells_dvt;
pub mod wells_pe;
pub mod wilks;
